"""link session exercises/sets to template

Revision ID: 986e5a82f446
Revises: c632c076cf42
Create Date: 2026-01-23 18:41:36.046666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '986e5a82f446'
down_revision: Union[str, Sequence[str], None] = 'c632c076cf42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_template_sets_template_exercise_id'), table_name='workout_template_sets')
    op.drop_table('workout_template_sets')
    op.add_column('workout_exercises', sa.Column('source_template_exercise_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_workout_exercises_source_template_exercise_id'), 'workout_exercises', ['source_template_exercise_id'], unique=False)
    op.add_column('workout_sets', sa.Column('source_template_set_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_workout_sets_source_template_set_id'), 'workout_sets', ['source_template_set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_sets_source_template_set_id'), table_name='workout_sets')
    op.drop_column('workout_sets', 'source_template_set_id')
    op.drop_index(op.f('ix_workout_exercises_source_template_exercise_id'), table_name='workout_exercises')
    op.drop_column('workout_exercises', 'source_template_exercise_id')
    op.create_table('workout_template_sets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('template_exercise_id', sa.INTEGER(), nullable=False),
    sa.Column('set_number', sa.INTEGER(), nullable=False),
    sa.Column('reps', sa.INTEGER(), nullable=True),
    sa.Column('weight_kg', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_template_sets_template_exercise_id'), 'workout_template_sets', ['template_exercise_id'], unique=False)
    # ### end Alembic commands ###
